### ISSUE TITLE
Discontinued?

### ISSUE THREAD

**Issue by fsmaia** [goerwin/directory-validator#2]
Hey there!

I was thinking about creating a tool like this one and, in my opinion, it had a huge potential to become super popular, because **every** file structure convention should have a CLI like this to rely on. I'm wondering why it isn't so.

In your opinion, what are the reasons for this? Is there another tool or library replacing it? Or simply the community is not that interested in lint folder/file structures?

**Comment by goerwin** [comment]
hey @fsmaia 

This project was intended to help me in my personal and work projects, so I wasn't really thinking about the popularity or that it could have. Although I put it out there in case anyone would find it useful.

I'm not sure about why the community, especially the Javascript one, is not interested but I have seen similar tools for other languages, especially strongly typed ones (C, Java, etc) in the past.
