### ISSUE TITLE
Prints just one line upon error

### ISSUE THREAD

**Issue by sturmery** [goerwin/directory-validator#9]
To make this tool useful for validating directory structure of Node.js projects, the only missing part seems to be printing the actual directory/file tree in green & red colors, as it happens with unit test code coverage.  Exiting after one mismatch doesn't provide the much needed insight into the whole structure.

I could try to patch it up a bit if you'd be willing to make a new release with those features built into it.  Please let me know.

**Comment by goerwin** [comment]
I Like the idea, if you want to go ahead and implement it, sure you can. I haven't added anything new since it is enough for my needs.
